= WiFi Link Library for Arduino WiFi Boards running WiFi Link Firmware

This library allows Arduino WiFi Boards to connect to the internet

For more information about this library please visit us at
http://www.arduino.org/learning/reference/wifilink


== License ==

Copyright (c) 2016 - 2017 Arduino Srl. All right reserved.
based on the original WiFiShield Library

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
